spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
  h2.console.enabled: true
  
logging.level.org.springframework: INFO
server.port: 8081
mensaje.bienvenida: ¡Hola desde configuración centralizada!

# El path interno del microservicio debe seguir siendo el estándar
springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html
  swagger-ui.use-root-path: true

keycloak:
  url: ${KEYCLOAK_EXTERNAL_URL}
  realm: ${KEYCLOAK_REALM}

gateway.url: ${GATEWAY_URL}
